'use client';
import { useState } from 'react';

const profiles={m1:{name:'Alex',month:'Month 1',streak:6,progress:24,state:'Building the habit'},risk:{name:'Sarah',month:'Month 2',streak:2,progress:46,state:'Getting back on track'},engaged:{name:'Mike',month:'Month 4',streak:21,progress:78,state:'Keeping momentum'}};
const shop=[['Dose for your Liver','Targets liver function & enzyme levels*'],['Dose for Cholesterol','Targets LDL, HDL & triglycerides*'],['Liver & Cholesterol Bundle','Support two core systems together*'],['All Doses','Explore the Dose lineup']];
const science=[['Formulations','How Dose combines plant-powered formulas with clinical research.'],['Ingredients','Explore the ingredients and extracts inside each Dose.'],['Clinical Studies','Review the research behind measurable results.']];
const more=[['Reviews','Stories and results from verified Dose customers.'],['Refer & Earn','Share Dose and earn rewards.'],['FAQs','Ingredients, orders, shipping, usage, subscriptions and more.'],['Track Orders','See where your next Dose is.'],['Contact','Get help from the Dose care team.'],['Store Locator','Find Dose near you.'],['HSA/FSA','Learn about eligible purchases.']];

export default function Home(){
 const[profileKey,setProfileKey]=useState('m1'),[taken,setTaken]=useState(false),[page,setPage]=useState('Today'),[menu,setMenu]=useState(false); const p=profiles[profileKey];
 const go=x=>{setPage(x);setMenu(false);window.scrollTo({top:0,behavior:'smooth'})};
 const Directory=({title,intro,items})=><><section className="pageHero"><p className="kicker">DOSE</p><h1>{title}</h1><p>{intro}</p></section><section className="directory">{items.map(([a,b])=><button className="directoryCard" key={a} onClick={()=>go(a)}><span><strong>{a}</strong><small>{b}</small></span><b>→</b></button>)}</section></>;
 const Detail=({title})=><><section className="pageHero"><p className="kicker">EXPLORE DOSE</p><h1>{title}</h1><p>This V0 area mirrors the corresponding Dose website destination. Production content and transactional connections can be added as a fast follow.</p></section><section className="panel clinical"><p className="kicker">THE DOSE STANDARD</p><h2>Plant-powered. Science-backed.</h2><p>Dose is built around supporting the body’s core systems with clinically studied formulas designed for measurable results.*</p><button className="blackBtn" onClick={()=>go('Science')}>Explore the science</button></section></>;
 const Today=()=> <><section className="memberHero"><p className="kicker">MY DOSE · {p.month.toUpperCase()}</p><h1>Good afternoon,<br/>{p.name}.</h1><p>{p.state}</p></section><section className="panel daily"><div><p className="kicker light">TODAY</p><h2>{taken?'Daily Dose complete ✓':'Ready for today’s Dose?'}</h2><p>{taken?`You’re building momentum. Current streak: ${p.streak+1} days.`:'Small daily actions add up. Check in after you take your Dose.'}</p></div><button className="limeBtn" onClick={()=>setTaken(!taken)}>{taken?'Completed':'I took my Dose'}</button></section><section className="twoCol"><article className="panel"><p className="kicker">YOUR PROGRESS</p><h2>{p.progress}% through this stage</h2><div className="track"><i style={{width:`${p.progress}%`}}/></div><button className="textBtn" onClick={()=>go('Progress')}>See my progress →</button></article><article className="panel"><p className="kicker">NEXT ORDER</p><h2>Your plan is active</h2><p>Review your upcoming Dose, shipment and subscription options.</p><button className="textBtn" onClick={()=>go('Account')}>Manage my plan →</button></article></section><section className="panel result"><p className="kicker">MEASURABLE RESULTS</p><h2>Know what to look for.</h2><p>Explore the clinical research behind liver and cholesterol markers including ALT, AST, ALP, GGT, LDL, HDL and triglycerides.</p><div className="markerRow"><span>ALT</span><span>AST</span><span>GGT</span><span>LDL</span></div><button className="blackBtn" onClick={()=>go('Clinical Studies')}>See the studies</button></section></>;
 const Progress=()=> <><section className="pageHero"><p className="kicker">YOUR JOURNEY</p><h1>Progress is built daily.</h1><p>Follow your consistency, check-ins and milestones across your Dose journey.</p></section><section className="panel"><div className="bigStat">{taken?p.streak+1:p.streak}</div><p>day current streak</p><div className="track"><i style={{width:`${p.progress}%`}}/></div><p>{p.progress}% through {p.month}</p></section><section className="panel"><p className="kicker">CHECK-IN</p><h2>How are you feeling?</h2><div className="choiceRow"><button>Better</button><button>Same</button><button>Not sure</button></div></section></>;
 const Account=()=> <><section className="pageHero"><p className="kicker">MY PLAN</p><h1>Your Dose, in one place.</h1><p>V0 demonstrates the account experience. Skio and Shopify actions can be connected after the demo.</p></section><section className="panel"><p className="kicker">SUBSCRIPTION</p><h2>Dose for your Liver</h2><p>Active · Ships every 24 days</p><div className="accountActions"><button>View next order</button><button>Skip shipment</button><button>Change plan</button></div></section><section className="panel"><p className="kicker">CARE</p><h2>We actually care.</h2><p>Get support, explore FAQs or connect with the Dose care team.</p><button className="blackBtn" onClick={()=>go('Contact')}>Get support</button></section></>;
 const Rewards=()=> <><section className="pageHero"><p className="kicker">REWARDS</p><h1>Consistency should feel rewarding.</h1><p>A V0 concept for loyalty, referrals and surprise-and-delight benefits.</p></section><section className="panel reward"><p className="kicker">YOUR STATUS</p><div className="bigStat">450</div><p>demo points</p><button className="limeBtn">Explore rewards</button></section><section className="panel"><p className="kicker">REFER & EARN</p><h2>Share your Dose.</h2><p>Referral is part of the current Dose site architecture and becomes a native member destination here.</p></section></>;
 let content=page==='Today'?<Today/>:page==='Progress'?<Progress/>:page==='Shop'?<Directory title="Shop Dose" intro="Doctor-formulated liquid supplements for the core systems quietly powering your body." items={shop}/>:page==='Science'?<Directory title="The science behind Dose" intro="Traditional principles meet modern, clinically backed research." items={science}/>:page==='Learn'?<Directory title="Learn" intro="Understand your body, your formula and what measurable progress can look like." items={[...science,['FAQs','Answers about ingredients, usage, subscriptions and more.']]}/>:page==='Rewards'?<Rewards/>:page==='Account'?<Account/>:page==='More'?<Directory title="More from Dose" intro="Support, community and everything else from the Dose ecosystem." items={more}/>:<Detail title={page}/>;
 return <main className="shell"><div className="promo">SUBSCRIBE + SAVE 30% | FREE SHIPPING ON ALL ORDERS</div><header className="topbar"><button className="wordmark" onClick={()=>go('Today')}>Dose</button><div className="desktopNav"><button onClick={()=>go('Shop')}>Shop Now</button><button onClick={()=>go('Science')}>Science</button><button onClick={()=>go('Reviews')}>Reviews</button><button onClick={()=>go('Rewards')}>Refer & Earn</button></div><button className="avatar" onClick={()=>go('Account')}>{p.name[0]}</button></header><section className="demoBar"><span>V0 DEMO</span><select value={profileKey} onChange={e=>{setProfileKey(e.target.value);setTaken(false)}}><option value="m1">Month 1 · Active</option><option value="risk">Month 2 · At risk</option><option value="engaged">Month 4 · Engaged</option></select></section>{content}<footer><strong>Dose</strong><p>Supporting your body’s core systems in a way that fits real life.</p><div><button onClick={()=>go('FAQs')}>FAQs</button><button onClick={()=>go('Track Orders')}>Track Orders</button><button onClick={()=>go('Contact')}>Contact</button><button onClick={()=>go('Store Locator')}>Store Locator</button></div><small>*Demo experience. Product statements shown for design continuity are subject to Dose’s official claims, terms and disclaimers.</small></footer><nav className="appNav"><button className={page==='Today'?'active':''} onClick={()=>go('Today')}>Today</button><button className={page==='Shop'?'active':''} onClick={()=>go('Shop')}>Shop</button><button className={page==='Science'||page==='Learn'?'active':''} onClick={()=>go('Science')}>Science</button><button className={page==='Rewards'?'active':''} onClick={()=>go('Rewards')}>Rewards</button><button className={page==='More'?'active':''} onClick={()=>go('More')}>More</button></nav></main>
}