'use client';
import { useMemo, useState } from 'react';
import SplashScreen from './components/SplashScreen';
import MemberPortal from './components/MemberPortal';

const LIVER='https://cdn.shopify.com/s/files/1/0348/3317/0477/files/liver-alt-media-bottle-no-badge.png?v=1770661532&width=900';
const LIVER_LIFE='https://dosedaily.co/cdn/shop/files/liver-home-product-section-up_900x.jpg?v=1613554269';
const CHOL='https://dosedaily.co/cdn/shop/files/cholesterol-alt-media-bottle.png?v=1770054243&width=900';
const profiles={m1:{name:'Alex',day:18,month:1,streak:6,points:1240},risk:{name:'Sarah',day:43,month:2,streak:2,points:760},engaged:{name:'Mike',day:104,month:4,streak:21,points:2860}};
const milestones=[['Month 1','Build the habit','Your first phase is about consistent daily intake and learning your routine.'],['Month 3','Look for shifts','A meaningful checkpoint for how you feel and for reviewing measurable progress.'],['Month 6','Check your numbers','A natural point to review bloodwork and compare how your numbers are trending.'],['Month 12','Your new baseline','A full year of consistent routine and long-term support.']];
const tips=[
 ['Make it automatic','Keep your Dose beside something you already use every morning. Habit stacking makes consistency easier.'],
 ['Consistency beats perfection','Missing one day does not erase your progress. The goal is to return to the routine the next day.'],
 ['Use your shipment as a cue','When a new bottle arrives, take a moment to check your next order date so your supply stays aligned.'],
 ['Learn one thing at a time','A three-minute lesson can be more useful than trying to absorb everything about your formula at once.'],
 ['Notice the routine first','Early progress can begin with consistency itself. Your Month-by-Month journey sets expectations for what comes next.']
];
const badgeCatalog=[
 {id:'starter',icon:'7',name:'7-Day Starter',description:'Take Dose 7 days in a row',goal:7,type:'streak'},
 {id:'cycle',icon:'24',name:'Full Cycle',description:'Complete 24 consistent days',goal:24,type:'streak'},
 {id:'learner',icon:'3',name:'Dose Scholar',description:'Complete all 3 Masterclass lessons',goal:3,type:'lessons'},
 {id:'reviewer',icon:'★',name:'Community Voice',description:'Share your first product review',goal:1,type:'review'},
];
const tierCatalog=[
 {name:'Bronze',min:0,max:1499},
 {name:'Silver',min:1500,max:2999},
 {name:'Gold',min:3000,max:4999},
];
const giftCatalog=[
 {id:'cycle-gift',day:24,title:'First Cycle',gift:'250 bonus points',detail:'A small boost for finishing your first full routine cycle.'},
 {id:'travel-case',day:72,title:'Order 3 milestone',gift:'Dose Travel Case',detail:'A purposeful travel gift designed to help keep your routine consistent away from home.'},
 {id:'ninety-day',day:90,title:'90-Day Routine',gift:'$10 member credit',detail:'A prototype milestone benefit for reaching the first major retention window.'},
];

export default function Home(){
 const[profileKey,setProfileKey]=useState('m1'),[page,setPage]=useState('Today'),[splash,setSplash]=useState(true),[taken,setTaken]=useState(false),[added,setAdded]=useState(false),[reviewed,setReviewed]=useState(false),[lessonCount,setLessonCount]=useState(1),[wearableConnected,setWearableConnected]=useState(false);const p=profiles[profileKey];
 const go=x=>{setPage(x);window.scrollTo({top:0,behavior:'smooth'})};
 const currentStreak=p.streak+(taken?1:0);
 const points=p.points+(taken?15:0)+(reviewed?100:0)+Math.max(0,lessonCount-1)*25;
 const tip=tips[p.day%tips.length];
 const nextReward=Math.ceil((points+1)/500)*500;
 const rewardProgress=Math.min(100,Math.round((points%500)/500*100));
 const cashback=Math.floor(points/1000)*5;
 const badges=useMemo(()=>badgeCatalog.map(b=>{
   const value=b.type==='streak'?currentStreak:b.type==='lessons'?lessonCount:reviewed?1:0;
   return {...b,value,progress:Math.min(100,Math.round(value/b.goal*100)),unlocked:value>=b.goal};
 }),[currentStreak,lessonCount,reviewed]);
 const unlocked=badges.filter(b=>b.unlocked).length;
 const tier=tierCatalog.find(t=>points>=t.min&&points<=t.max)||{name:'Gold',min:3000,max:4999};
 const nextTier=tier.name==='Bronze'?'Silver':tier.name==='Silver'?'Gold':'Gold';
 const tierFloor=tier.min;
 const tierCeiling=tier.max+1;
 const tierProgress=tier.name==='Gold'?100:Math.min(100,Math.round((points-tierFloor)/(tierCeiling-tierFloor)*100));
 const pointsToTier=tier.name==='Gold'?0:tierCeiling-points;
 const leaderboard=[
   {name:'Maya R.',points:3180,streak:29},
   {name:'Jordan K.',points:2940,streak:26},
   {name:p.name+' · You',points,streak:currentStreak,you:true},
   {name:'Sam T.',points:1670,streak:14},
   {name:'Chris L.',points:1425,streak:11},
 ].sort((a,b)=>b.points-a.points).map((x,i)=>({...x,rank:i+1}));

 if(splash)return <SplashScreen name={p.name} onContinue={()=>{setSplash(false);setPage('You')}}/>;
 const Header=()=> <><header className="appHeader"><button className="logo" onClick={()=>go('Today')}>Dose</button><span className="demoPill">Member</span><button className="avatar" onClick={()=>go('You')}>{p.name[0]}</button></header><div className="profileSwitch"><span>Demo profile</span><select value={profileKey} onChange={e=>{setProfileKey(e.target.value);setTaken(false);setReviewed(false);setLessonCount(1);setWearableConnected(false)}}><option value="m1">Month 1 · Active</option><option value="risk">Month 2 · At risk</option><option value="engaged">Month 4 · Engaged</option></select></div></>;

 const Today=()=> <div className="page"><section className="welcome compact"><div><span className="eyebrow">Day {p.day} · Your liver journey</span><h1>Good afternoon,<br/>{p.name}.</h1><p>Here's what matters today.</p></div><img src={LIVER} alt="Dose for your Liver"/></section>
 <section className={taken?'todayAction done':'todayAction'}><div className="checkIcon">{taken?'✓':'○'}</div><div><span className="eyebrow light">Today</span><h2>{taken?'Daily Dose complete':'Take your daily Dose'}</h2><p>{taken?`${currentStreak} day streak. +15 points earned.`:`You're ${Math.max(0,7-p.streak)} day${7-p.streak===1?'':'s'} from your 7-Day Starter badge.`}</p></div><button onClick={()=>setTaken(!taken)}>{taken?'Done':'I took it'}</button></section>
 <section className="streakStrip"><div><span className="streakFlame">✦</span><div><strong>{currentStreak} day streak</strong><small>{Math.max(0,7-currentStreak)} days to your next badge</small></div></div><div className="miniBadgeProgress"><span><i style={{width:`${Math.min(100,currentStreak/7*100)}%`}}/></span><b>{Math.min(currentStreak,7)}/7</b></div></section>
 <section className="dailyTip"><span className="tipLabel">Daily tip</span><h2>{tip[0]}</h2><p>{tip[1]}</p></section>
 <section className="rewardSnapshot"><div className="rewardSnapshotTop"><div><span className="eyebrow">Dose Rewards · {tier.name}</span><h2>{points.toLocaleString()} points</h2><p>${cashback} cash back available · {unlocked}/{badges.length} badges unlocked</p></div><button onClick={()=>go('Rewards')}>View rewards</button></div><div className="rewardMeter"><div><i style={{width:`${rewardProgress}%`}}/></div><span>{Math.max(0,nextReward-points)} points to your next reward milestone</span></div></section>
 <section className="expectationCard" onClick={()=>go('Journey')}><span className="eyebrow">What to expect</span><h2>You're in Month {p.month}.</h2><p>{milestones[Math.min(p.month-1,3)][2]}</p><strong>See your results timeline →</strong></section>
 <div className="sectionHead"><div><span className="eyebrow">Keep going</span><h2>Continue learning.</h2></div><button onClick={()=>go('Learn')}>See all</button></div><button className="learningHero slim" onClick={()=>go('Learn')}><div className="learningImage"><img src={LIVER_LIFE} alt="Dose education"/><span>Your program</span></div><div className="learningCopy"><span className="eyebrow">Liver Masterclass</span><h3>What to expect in Month 1</h3><p>Build the habit, understand your product, and know when results become meaningful.</p><strong>{lessonCount}/3 complete · Continue →</strong></div></button>
 <div className="sectionHead"><div><span className="eyebrow">Your order</span><h2>On the way.</h2></div><button onClick={()=>go('Orders')}>Track</button></div><button className="orderStatus" onClick={()=>go('Orders')}><div className="orderIcon">▣</div><div><span>Arriving Oct 1–3</span><strong>Dose for your Liver</strong><small>Shipped · In transit</small></div><b>›</b></button></div>;

 const Learn=()=> <div className="page"><section className="simpleHero"><span className="eyebrow">Learn</span><h1>Know your Dose.</h1><p>Product education, expectations, and clinical context in one place.</p></section><section className="learnFeatured"><img src={LIVER_LIFE} alt="Dose for your Liver"/><div><span className="eyebrow">Start here</span><h2>Dose for your Liver</h2><p>Learn how to take it, what's inside, and how to think about progress over time.</p><div className="chips"><span>2 oz daily shot</span><span>Plant-based</span><span>Month-by-month guidance</span></div></div></section><div className="sectionHead"><div><span className="eyebrow">Liver Masterclass</span><h2>Learn in 3 quick steps.</h2></div><span className="lessonReward">+25 pts each</span></div><section className="lessonRail">{['Meet your daily Dose','What to expect in Month 1','How to measure progress'].map((t,i)=>{const complete=i<lessonCount;return <button className={complete?'lessonTile lessonDone':'lessonTile'} key={t} onClick={()=>setLessonCount(Math.max(lessonCount,i+1))}><div className="lessonCover"><span>0{i+1}</span><small>{complete?'Complete':'Liver health'}</small></div><div><small>Day {i+1} · {i===1?'4':'3'} min</small><strong>{t}</strong><span>{complete?'✓ Complete':'+25 pts · Complete lesson →'}</span></div></button>})}</section><button className="journeyCta roomyCta" onClick={()=>go('Journey')}><span>Results timeline</span><strong>See what to expect at Month 1, 3, 6 and 12</strong><b>→</b></button></div>;

 const Journey=()=> <div className="page"><section className="simpleHero"><span className="eyebrow">What to expect</span><h1>Results build<br/>with consistency.</h1><p>Your app should help set expectations clearly so customers know what each phase of the journey means.</p></section><section className="journeyTimeline">{milestones.map((x,i)=><article key={x[0]} className={i===0?'current':''}><div className="milestoneDot">{i+1}</div><div><span>{x[0]}</span><h2>{x[1]}</h2><p>{x[2]}</p></div></article>)}</section></div>;

 const Orders=()=> <div className="page"><section className="simpleHero"><span className="eyebrow">Orders</span><h1>Know exactly<br/>where it is.</h1><p>Track the order that keeps your routine going.</p></section><section className="trackingCard"><div className="trackingTop"><span className="status live">In transit</span><span>#DOSE-28491</span></div><img src={LIVER} alt="Dose order"/><h2>Arriving Oct 1–3</h2><p>Dose for your Liver · 1 bottle</p><div className="trackSteps"><div className="complete"><i>✓</i><span><strong>Order confirmed</strong><small>September 28</small></span></div><div className="complete"><i>✓</i><span><strong>Shipped</strong><small>September 29</small></span></div><div className="active"><i>•</i><span><strong>In transit</strong><small>On the way to you</small></span></div><div><i>○</i><span><strong>Delivered</strong><small>Estimated Oct 1–3</small></span></div></div><button className="primary spaciousPrimary" onClick={()=>go('Plan')}>Manage next order</button></section></div>;

 const Discover=()=> <div className="page"><section className="simpleHero"><span className="eyebrow">Discover</span><h1>Build a routine<br/>for your goals.</h1><p>Explore complementary Dose products from inside the member experience.</p></section><article className="productDiscovery"><div className="productVisual"><span className="recommend">Recommended</span><img src={CHOL} alt="Dose for Cholesterol"/></div><div className="productInfo"><span className="eyebrow">Pairs with your liver routine</span><h2>Dose for Cholesterol</h2><p>Targeted support for healthy cholesterol levels and lipid processing.*</p><div className="productBottom"><div><small>Subscriber add-on</small><strong>From $63 / 24 days</strong></div><button onClick={()=>setAdded(!added)}>{added?'✓ Added':'Add to next order'}</button></div></div></article></div>;

 const Plan=()=> <div className="page"><section className="simpleHero"><span className="eyebrow">My plan</span><h1>Your routine,<br/>on your terms.</h1><p>Manage the subscription behind your daily habit.</p></section><section className="planProduct"><div className="productImage"><img src={LIVER} alt="Dose for your Liver"/></div><div><span className="status">Active</span><h2>Dose for your Liver</h2><p>1 bottle every 24 days</p></div></section><section className="nextOrder"><span className="eyebrow">Next order</span><div><strong>September 28</strong><span>Estimated delivery Oct 1–3</span></div><button onClick={()=>go('Orders')}>Track order</button></section></div>;

 const Rewards=()=> <div className="page rewardsPage"><section className="simpleHero rewardsHero"><span className="eyebrow">Dose Rewards</span><h1>Your routine<br/>pays you back.</h1><p>Build consistency, learn about your health, share feedback, and unlock member benefits along the way.</p></section>
 <section className="levelCard"><div className={`levelMedal ${tier.name.toLowerCase()}`}>{tier.name[0]}</div><div className="levelCopy"><span className="eyebrow">Member level</span><h2>{tier.name}</h2><p>{tier.name==='Gold'?'You reached our current top prototype level.':`${pointsToTier.toLocaleString()} points to ${nextTier}.`}</p><div className="tierTrack"><i style={{width:`${tierProgress}%`}}/></div><small>{tier.name==='Gold'?'Gold unlocked':`${tierProgress}% complete`}</small></div></section>
 <section className="rewardsBalance"><div><span>Current balance</span><strong>{points.toLocaleString()}</strong><small>points</small></div><div><span>Cash back</span><strong>${cashback}</strong><small>available</small></div><div><span>Badges</span><strong>{unlocked}/{badges.length}</strong><small>unlocked</small></div></section>
 <section className="rewardGoal"><div className="rewardGoalCopy"><span className="eyebrow">Next reward</span><h2>{Math.max(0,nextReward-points)} points to go.</h2><p>Keep taking your Dose, learning, and sharing feedback to reach your next milestone.</p></div><div className="rewardMeter large"><div><i style={{width:`${rewardProgress}%`}}/></div><span>{points.toLocaleString()} / {nextReward.toLocaleString()} pts</span></div></section>
 <div className="sectionHead"><div><span className="eyebrow">Milestone gifts</span><h2>Something worth reaching.</h2></div></div><section className="giftRail">{giftCatalog.map(g=>{const progress=Math.min(100,Math.round(p.day/g.day*100));const unlockedGift=p.day>=g.day;return <article className={unlockedGift?'giftCard unlocked':'giftCard'} key={g.id}><div className="giftIcon">{g.id==='travel-case'?'▣':unlockedGift?'✓':'◌'}</div><div><span>{unlockedGift?'Unlocked':`${Math.max(0,g.day-p.day)} days to go`}</span><h3>{g.gift}</h3><strong>{g.title}</strong><p>{g.detail}</p><div className="giftProgress"><i style={{width:`${progress}%`}}/></div><small>{Math.min(p.day,g.day)}/{g.day} journey days</small></div></article>})}</section>
 <div className="sectionHead"><div><span className="eyebrow">Badges</span><h2>Keep the streak alive.</h2></div></div><section className="badgeGrid">{badges.map(b=><article className={b.unlocked?'badgeCard unlocked':'badgeCard'} key={b.id}><div className="badgeMedal"><span>{b.unlocked?'✓':b.icon}</span></div><div className="badgeCopy"><span>{b.unlocked?'Unlocked':'In progress'}</span><h3>{b.name}</h3><p>{b.description}</p><div className="badgeBar"><i style={{width:`${b.progress}%`}}/></div><small>{Math.min(b.value,b.goal)}/{b.goal}</small></div></article>)}</section>
 <div className="sectionHead"><div><span className="eyebrow">Dose Circle</span><h2>Your weekly leaderboard.</h2></div><span className="privateLabel">Opt-in aliases</span></div><section className="leaderboard"><div className="leaderboardHead"><span>Rank</span><span>Member</span><span>Streak</span><span>Points</span></div>{leaderboard.map(r=><div className={r.you?'leaderRow you':'leaderRow'} key={r.name}><b>#{r.rank}</b><span>{r.name}</span><small>{r.streak} days</small><strong>{r.points.toLocaleString()}</strong></div>)}<p>Prototype leaderboard uses aliases and should be opt-in in production. No real customer data is shown.</p></section>
 <div className="sectionHead"><div><span className="eyebrow">Connected wellness</span><h2>Bring your routine together.</h2></div></div><section className={wearableConnected?'wearableCard connected':'wearableCard'}><div className="wearableHeader"><div className="watchMark">⌚</div><div><span className="eyebrow">Apple Watch + Apple Health</span><h3>{wearableConnected?'Connected':'Connect your wearable'}</h3><p>{wearableConnected?'Demo wellness signals are now shown alongside your Dose routine.':'Future integration can use member-authorized Apple Health data to add context around activity, sleep, and routine consistency.'}</p></div></div>{wearableConnected?<div className="wearableStats"><div><span>Steps</span><strong>8,432</strong></div><div><span>Sleep</span><strong>7h 21m</strong></div><div><span>Resting HR</span><strong>64</strong></div></div>:null}<button onClick={()=>setWearableConnected(!wearableConnected)}>{wearableConnected?'Disconnect demo':'Connect Apple Health'}</button><small className="wearableNote">Prototype only. A real Apple Watch/Health integration requires an approved native HealthKit implementation and explicit member permission.</small></section>
 <div className="sectionHead"><div><span className="eyebrow">Earn more</span><h2>Small actions, more value.</h2></div></div><section className="earnList"><article><div className="earnIcon">✓</div><div><strong>Take your daily Dose</strong><small>Build consistency and your streak</small></div><b>+15 pts</b></article><article><div className="earnIcon">□</div><div><strong>Complete a lesson</strong><small>{lessonCount}/3 Masterclass lessons complete</small></div><b>+25 pts</b></article><article><div className="earnIcon">★</div><div><strong>Review your Dose</strong><small>{reviewed?'Thanks for sharing your experience':'Help other members know what to expect'}</small></div>{reviewed?<b>+100 pts ✓</b>:<button onClick={()=>setReviewed(true)}>Write review · +100</button>}</article><article><div className="earnIcon">↗</div><div><strong>Refer a friend</strong><small>Share Dose with someone in your circle</small></div><b>Bonus</b></article></section>
 <section className="rewardDisclaimer"><strong>Prototype rewards model</strong><p>Points, cash-back values, tier thresholds, leaderboard positions, milestone gifts, and review rewards shown here are illustrative until final loyalty economics and system-of-record rules are approved.</p></section></div>;

 let content=page==='Today'?<Today/>:page==='Learn'?<Learn/>:page==='Journey'?<Journey/>:page==='Orders'?<Orders/>:page==='Discover'?<Discover/>:page==='Plan'?<Plan/>:page==='Rewards'?<Rewards/>:<MemberPortal name={p.name} streak={currentStreak} points={points} cashback={cashback} onNavigate={go}/>;
 return <main className="appShell"><Header/>{content}<nav className="bottomNav"><button className={page==='Today'||page==='Rewards'?'active':''} onClick={()=>go('Today')}><span>⌂</span>Today</button><button className={page==='Learn'||page==='Journey'?'active':''} onClick={()=>go('Learn')}><span>□</span>Learn</button><button className={page==='Orders'?'active':''} onClick={()=>go('Orders')}><span>▣</span>Orders</button><button className={page==='Discover'?'active':''} onClick={()=>go('Discover')}><span>◇</span>Discover</button><button className={page==='You'||page==='Plan'?'active':''} onClick={()=>go('You')}><span>○</span>You</button></nav></main>
}